<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RazorpierFormatOnBuild>true</RazorpierFormatOnBuild>
    <RazorpierMSBuildAssembly>$(MSBuildProjectDirectory)/../../../src/Razorpier.MSBuild/bin/Debug/netstandard2.0/Razorpier.MSBuild.dll</RazorpierMSBuildAssembly>
  </PropertyGroup>

  <Import Project="../../../src/Razorpier.MSBuild/buildTransitive/Razorpier.MSBuild.targets" />
</Project>
